// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mttechne.Backend.Junior.Services.Data;

#nullable disable

namespace Mttechne.Backend.Junior.Services.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240113000341_Teste2")]
    partial class Teste2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Mttechne.Backend.Junior.Services.Model.Produto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(1);

                    b.Property<int>("Valor")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.HasKey("ID");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Nome = "Placa de Vídeo",
                            Valor = 1000
                        },
                        new
                        {
                            ID = 2,
                            Nome = "Placa de Vídeo",
                            Valor = 1500
                        },
                        new
                        {
                            ID = 3,
                            Nome = "Placa de Vídeo",
                            Valor = 1350
                        },
                        new
                        {
                            ID = 4,
                            Nome = "Processador",
                            Valor = 2000
                        },
                        new
                        {
                            ID = 5,
                            Nome = "Processador",
                            Valor = 2100
                        },
                        new
                        {
                            ID = 6,
                            Nome = "Memória",
                            Valor = 300
                        },
                        new
                        {
                            ID = 7,
                            Nome = "Memória",
                            Valor = 350
                        },
                        new
                        {
                            ID = 8,
                            Nome = "Placa mãe",
                            Valor = 1100
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
